name: GitHub Actions Demo
run-name: Unit tests are running ! 🚀
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run test
